severity: error

linters:

  BorderZero:
    enabled: true
    convention: zero

  BemDepth:
    enabled: true

  DeclarationOrder:
    enabled: false

  ExtendDirective:
    enabled: true

  LeadingZero:
    enabled: false

  NameFormat:
    enabled: true

  PrivateNamingConvention:
    enabled: true
    prefix: _

  PropertySortOrder:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorFormat:
    enabled: false

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  StringQuotes:
    enabled: true
    style: single_quotes

  ColorVariable:
    enabled: false

  NoColorLiterals:
    enabled: false
  
  ColorKeyword:
    enabled: false

  UnnecessaryParentReference:
    enabled: false

  PseudoElement:
    enabled: false

  ImportantRule:
    enabled: false

  ImportPath:
    enabled: false

  NestingDepth:
    enabled: false

  SelectorDepth:
    enabled: false

  ZeroUnit:
    enabled: true

  Indentation:
    enabled: false

  VendorPrefix:
    enabled: false
