export const COPY = {
    TITLE: 'Basic Information',
    NAME: 'What is this learning object named?',
    NAMEPLACEHOLDER: 'Choose a succinct self-contained name that is unique amongst your learning objects.',
    LENGTH: 'How long should it take to complete this learning object?',
    CHOOSE: 'Choose from five different course types, each with a different length.',
    NANO: 'Nanomodule  - up to 1 hour',
    MICRO: 'Micromodule  - between 1 and 4 hours',
    MOD: 'Module - between 4 and 10 hours',
    UNIT: 'Unit - over 10 hours',
    COURSE: 'Course (15 Weeks)',
    LEVELS: 'What academic levels is this content suited for?',
    SELECT: 'Select as many levels as are appropriate.',
    QUESTION: 'How would you describe this learning object?',
    TIP: 'Be descriptive! You\'ll have a chance to enter notes later.',
};
