name: Branching Strategy to automate Pull Requests

#Only runs when a pull request is closed
on:
  pull_request:
    types: [closed]
    branches:
      - releases

jobs:
  Action-Information:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job was triggered by ${{ github.event_name }}."
      - run: echo "Current branch is ${{ github.ref }} in the ${{ github.repository }} repository."
      - run: echo "The job is being run on a ${{ runner.os }} server hosted by Github"
